[package]
publish = false
name = "qgram-index-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rayon = "1"
pyo3 = { version = "0", features = ["extension-module", "abi3-py310", "anyhow"] }
itertools = "0"
memmap2 = "0"
serde = { version = "1", features = ["derive"] }
rmp-serde = "1"

[profile.release]
lto = true
codegen-units = 1
strip = true
